import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="p-8">
          <nav className="mb-6 flex gap-4 text-sm">
            <Link href="/">Home</Link>
            <Link href="/chat">Chat</Link>
            <Link href="/approvals">Approvals</Link>
            <Link href="/settings">Settings</Link>
            <Link href="/tasks">Tasks</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
